name: light_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  injectable: ^2.2.0
  get_it: ^7.6.0
  cupertino_icons: ^1.0.2
  collection: ^1.17.1
  badges: ^3.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sansation
      fonts:
        - asset: assets/fonts/Sansation-Regular.ttf
        - asset: assets/fonts/Sansation-Italic.ttf
          style: italic
        - asset: assets/fonts/Sansation-Bold.ttf
          weight: 700